from .nodes.flexible_image_batch import (
    NODE_CLASS_MAPPINGS        as _BATCH_CLASS,
    NODE_DISPLAY_NAME_MAPPINGS as _BATCH_NAMES,
)
from .nodes.ram_cleanup import (
    NODE_CLASS_MAPPINGS        as _CLEANUP_CLASS,
    NODE_DISPLAY_NAME_MAPPINGS as _CLEANUP_NAMES,
)
from .nodes.output_path import (
    NODE_CLASS_MAPPINGS        as _PATH_CLASS,
    NODE_DISPLAY_NAME_MAPPINGS as _PATH_NAMES,
)

NODE_CLASS_MAPPINGS        = {**_BATCH_CLASS,  **_CLEANUP_CLASS, **_PATH_CLASS}
NODE_DISPLAY_NAME_MAPPINGS = {**_BATCH_NAMES,  **_CLEANUP_NAMES, **_PATH_NAMES}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
